create table author (id bigint auto_increment not null, bio varchar(255), birthdate timestamp(6), name varchar(255), website varchar(255), primary key (id));
create table book (isbn varchar(255) not null, avg_rating float(53) not null, language varchar(255), name varchar(255), publisher_id bigint, series_id bigint, sub_name varchar(255), primary key (isbn));
create table book_author (id bigint auto_increment not null, author_id bigint, book_id varchar(255), primary key (id));
create table book_genre (id bigint auto_increment not null, book_id varchar(255), genre varchar(255), primary key (id));
create table book_list (id bigint auto_increment not null, name varchar(255), primary key (id));
create table book_list_book (id bigint auto_increment not null, book_id varchar(255), list_id bigint, primary key (id));
create table profile (username varchar(255) not null, birthdate timestamp(6), email varchar(255), full_name varchar(255), password varchar(255), profile_pic varchar(255), primary key (username));
create table profile_book (id bigint auto_increment not null, book_id varchar(255), user_id varchar(255), primary key (id));
create table publisher (id bigint auto_increment not null, name varchar(255), primary key (id));
create table publisher_book (id bigint auto_increment not null, book_id varchar(255), publisher_id bigint, primary key (id));
create table review (id bigint auto_increment not null, book_id varchar(255), comment varchar(255), rate float(53) not null, user_id varchar(255), primary key (id));
create table series (id bigint auto_increment not null, name varchar(255), primary key (id));
create table series_book (id bigint auto_increment not null, book_id varchar(255), series_id bigint, primary key (id));
create table shelf (id bigint auto_increment not null, name varchar(255), user_id varchar(255), primary key (id));
create table shelf_book (id bigint auto_increment not null, book_id varchar(255), shelf_id bigint, primary key (id));
create table social_media (id bigint auto_increment not null, author_id bigint, type varchar(255), url varchar(255), primary key (id));
